(define (problem prob)
 (:domain cube)
 (:objects white yellow green blue orange red - colour b1 b2 b3 b4 b5 b6 b7 b8 - block)
 (:init 
 	(on b1 white orange blue)
 	(on b2 orange yellow green)
	(on b3 yellow red green)
	(on b4 green orange white)
	(on b5 red white green)
	(on b6 yellow red blue)
	(on b7 orange yellow blue)
	(on b8 blue white red)
)
 (:goal (and 
		(on b1 red yellow green)
		(on b2 red white green)
		(on b3 red yellow blue)
		(on b4 red white blue)
		(on b5 orange yellow green)
		(on b6 orange white green)
		(on b7 orange yellow blue)
		(on b8 orange white blue)
 	)
)
)