(define (problem prob)
 (:domain cube)
 (:objects white yellow green blue orange red - colour b1 b2 b3 b4 b5 b6 b7 b8 - block)
 (:init 
 	(on b1 yellow orange green)
 	(on b2 red blue white)
	(on b3 orange blue yellow)
	(on b4 red green white)
	(on b5 white orange green)
	(on b6 red yellow green)
	(on b7 yellow red blue)
	(on b8 blue orange white)
)
 (:goal (and 
		(on b1 white red green)
		(on b2 white orange green)
		(on b3 white red blue)
		(on b4 white orange blue)
		(on b5 yellow red green)
		(on b6 yellow orange green)
		(on b7 yellow red blue)
		(on b8 yellow orange blue)
 	)
)
)