(define (problem prob)
 (:domain cube)
 (:objects white yellow green blue orange red - colour b1 b2 b3 b4 b5 b6 b7 b8 - block)
 (:init 
 	(on b1 yellow green red)
 	(on b2 orange yellow green)
	(on b3 orange blue yellow)
	(on b4 orange white green)
	(on b5 yellow blue red)
	(on b6 blue red white)
	(on b7 orange blue white)
	(on b8 green red white)
)
 (:goal (and 
		(on b1 red blue yellow)
		(on b2 red green yellow)
		(on b3 red blue white)
		(on b4 red green white)
		(on b5 orange blue yellow)
		(on b6 orange green yellow)
		(on b7 orange blue white)
		(on b8 orange green white)
 	)
)
)